import React, { useRef, useState } from 'react';
import { Link } from 'react-router-dom';
import { Helmet } from 'react-helmet-async';
import { Gauge, Check, X, RotateCcw, ArrowRight, Wifi } from 'lucide-react';
import SEO from '../components/SEO';

// Free IPTV speed test: latency/jitter + multi-stream download from our own
// CDN (payloads generated by scripts/gen-speedtest.mjs), then a verdict per
// video quality. Capped at 8 s / 32 MB per test to keep bandwidth costs low.

const SITE_URL = 'https://franceiptv.stream';
const PING_URL = '/speedtest/ping.txt';
const PAYLOAD_URL = '/speedtest/payload-8mb.bin';
const MAX_MS = 8000;
const MAX_BYTES = 32 * 1024 * 1024;
const STREAMS = 4;

const QUALITIES = [
  { name: 'SD', need: 3, detail: 'Qualité standard, petits écrans' },
  { name: 'HD (720p)', need: 7, detail: 'Téléphone, tablette' },
  { name: 'Full HD (1080p)', need: 15, detail: 'Smart TV, sport en direct' },
  { name: '4K Ultra HD', need: 25, detail: 'Grand écran 4K, meilleure qualité' },
];

const faqs = [
  {
    q: "Quel débit faut-il pour regarder l'IPTV ?",
    a: "Comptez environ 3 Mbit/s pour la SD, 7 Mbit/s pour la HD, 15 Mbit/s pour la Full HD et 25 Mbit/s pour la 4K, par écran. Si plusieurs personnes regardent en même temps, additionnez ces valeurs. La stabilité de la connexion compte autant que le débit.",
  },
  {
    q: 'Ce test mesure-t-il la vitesse de ma box ou de mon appareil ?',
    a: "Il mesure la connexion de l'appareil sur lequel vous faites le test, y compris son Wi-Fi. Pour un résultat fidèle, lancez-le sur l'appareil qui sert à regarder l'IPTV (Smart TV avec navigateur, box Android, téléphone), à l'endroit où il se trouve.",
  },
  {
    q: "Pourquoi mon résultat est-il plus bas que l'offre de mon fournisseur internet ?",
    a: "L'offre de votre fournisseur est un maximum théorique. Le Wi-Fi, la distance avec la box, les murs, les autres appareils connectés et les heures de pointe réduisent le débit réel. En câble Ethernet, le résultat se rapproche de l'offre.",
  },
  {
    q: "Qu'est-ce que la latence (ping) et la gigue ?",
    a: "La latence est le temps de réponse de la connexion, en millisecondes. La gigue (jitter) mesure sa variation. Pour l'IPTV, une latence sous 100 ms et une gigue faible évitent les coupures et les chargements en boucle.",
  },
];

const schemas = [
  {
    '@context': 'https://schema.org',
    '@type': 'WebApplication',
    name: 'Test de débit IPTV',
    url: `${SITE_URL}/test-debit-iptv`,
    applicationCategory: 'UtilitiesApplication',
    operatingSystem: 'Tous (navigateur web)',
    offers: { '@type': 'Offer', price: '0', priceCurrency: 'EUR' },
    inLanguage: 'fr-FR',
    publisher: { '@type': 'Organization', name: 'France IPTV', url: SITE_URL },
  },
  {
    '@context': 'https://schema.org',
    '@type': 'FAQPage',
    mainEntity: faqs.map((f) => ({ '@type': 'Question', name: f.q, acceptedAnswer: { '@type': 'Answer', text: f.a } })),
  },
  {
    '@context': 'https://schema.org',
    '@type': 'BreadcrumbList',
    itemListElement: [
      { '@type': 'ListItem', position: 1, name: 'Accueil', item: SITE_URL },
      { '@type': 'ListItem', position: 2, name: 'Test de débit IPTV', item: `${SITE_URL}/test-debit-iptv` },
    ],
  },
];

const bust = (url) => `${url}?r=${Date.now()}-${Math.random().toString(36).slice(2)}`;

async function measurePing(samples = 8) {
  const times = [];
  for (let i = 0; i < samples; i += 1) {
    const start = performance.now();
    await fetch(bust(PING_URL), { cache: 'no-store' });
    times.push(performance.now() - start);
  }
  times.shift(); // first request includes connection setup
  const sorted = [...times].sort((a, b) => a - b);
  const ping = sorted[Math.floor(sorted.length / 2)];
  const jitter = times.slice(1).reduce((sum, t, i) => sum + Math.abs(t - times[i]), 0) / (times.length - 1);
  return { ping: Math.round(ping), jitter: Math.round(jitter) };
}

async function measureDownload(onProgress) {
  const controller = new AbortController();
  const start = performance.now();
  let bytes = 0;
  const stop = () => controller.abort();
  const timer = setTimeout(stop, MAX_MS);

  const stream = async () => {
    while (!controller.signal.aborted) {
      const res = await fetch(bust(PAYLOAD_URL), { cache: 'no-store', signal: controller.signal });
      const reader = res.body.getReader();
      for (;;) {
        const { done, value } = await reader.read();
        if (done) break;
        bytes += value.length;
        const secs = (performance.now() - start) / 1000;
        onProgress((bytes * 8) / secs / 1e6);
        if (bytes >= MAX_BYTES) stop();
      }
    }
  };

  await Promise.allSettled(Array.from({ length: STREAMS }, stream));
  clearTimeout(timer);
  const secs = (performance.now() - start) / 1000;
  return (bytes * 8) / secs / 1e6;
}

const formatMbps = (v) => (v >= 100 ? Math.round(v) : v.toFixed(1)).toString().replace('.', ',');

const TestDebit = () => {
  const [phase, setPhase] = useState('idle'); // idle | ping | download | done | error
  const [live, setLive] = useState(0);
  const [result, setResult] = useState(null);
  const running = useRef(false);

  const run = async () => {
    if (running.current) return;
    running.current = true;
    setResult(null);
    setLive(0);
    try {
      setPhase('ping');
      const { ping, jitter } = await measurePing();
      setPhase('download');
      const download = await measureDownload((v) => setLive(v));
      setResult({ download, ping, jitter });
      setPhase('done');
      window.gtag?.('event', 'speed_test', { download_mbps: Math.round(download), ping_ms: ping });
    } catch (e) {
      setPhase('error');
    } finally {
      running.current = false;
    }
  };

  const speed = phase === 'done' ? result.download : live;
  const gaugePct = Math.min(100, (speed / 30) * 100);
  const hdStreams = result ? Math.max(0, Math.floor(result.download / 7)) : 0;
  const pingOk = result && result.ping < 100 && result.jitter < 30;

  return (
    <>
      <SEO
        title="Test de Débit IPTV Gratuit : Votre Connexion Suffit-elle ?"
        description="Testez gratuitement votre débit pour l'IPTV : vitesse, latence et gigue, avec un verdict clair pour la SD, la HD, la Full HD et la 4K. Résultat en 10 secondes."
        keywords="test débit iptv, test vitesse iptv, débit iptv, quel débit pour iptv, test connexion iptv, débit 4k iptv"
        canonicalPath="/test-debit-iptv"
      />
      <Helmet>
        {schemas.map((s, i) => <script key={i} type="application/ld+json">{JSON.stringify(s)}</script>)}
      </Helmet>

      <div className="min-h-screen pt-24">
        <section className="px-4 pb-14">
          <div className="max-w-3xl mx-auto text-center">
            <p className="flex items-center justify-center gap-4 text-[11px] tracking-[0.28em] font-medium text-brand-black mb-5">
              <span className="inline-block w-10 h-px bg-brand-gold" /> OUTIL GRATUIT
            </p>
            <h1 className="text-4xl md:text-6xl text-brand-black leading-tight mb-4">Test de débit IPTV</h1>
            <p className="text-lg text-brand-gray max-w-xl mx-auto">
              Votre connexion est-elle assez rapide pour la HD ou la 4K ? Lancez le test sur l'appareil qui sert à regarder
              l'IPTV : résultat en une dizaine de secondes.
            </p>
          </div>

          <div className="max-w-xl mx-auto mt-10 rounded-2xl border border-brand-gray-border bg-surface p-6 md:p-8">
            <div className="text-center">
              <p className="text-sm text-brand-gray mb-1">Débit descendant</p>
              <p className="text-6xl md:text-7xl font-semibold tracking-tight text-brand-black tabular-nums">
                {phase === 'idle' || phase === 'ping' ? '–' : formatMbps(speed)}
                <span className="text-xl font-normal text-brand-gray"> Mbit/s</span>
              </p>
              <div className="h-2.5 rounded-full bg-surface-2 mt-5 overflow-hidden" aria-hidden="true">
                <div className="h-full bg-brand-gold transition-[width] duration-200" style={{ width: `${phase === 'idle' ? 0 : gaugePct}%` }} />
              </div>
              <div className="flex justify-between text-[11px] text-brand-gray mt-1.5">
                <span>0</span><span>HD 7</span><span>Full HD 15</span><span>4K 25+</span>
              </div>
              <p className="text-sm text-brand-gray mt-4 min-h-[20px]" aria-live="polite">
                {phase === 'ping' && 'Mesure de la latence…'}
                {phase === 'download' && 'Mesure du débit…'}
                {phase === 'done' && `Latence ${result.ping} ms · Gigue ${result.jitter} ms`}
                {phase === 'error' && 'Le test a échoué. Vérifiez votre connexion et réessayez.'}
              </p>
              <button
                type="button"
                onClick={run}
                disabled={phase === 'ping' || phase === 'download'}
                className="mt-5 w-full min-h-[54px] inline-flex items-center justify-center gap-3 bg-brand-gold hover:opacity-90 disabled:opacity-60 text-white font-semibold rounded-lg text-lg"
              >
                {phase === 'done' || phase === 'error' ? <><RotateCcw size={20} /> Relancer le test</> : <><Gauge size={22} /> {phase === 'idle' ? 'Lancer le test' : 'Test en cours…'}</>}
              </button>
            </div>

            {phase === 'done' && (
              <div className="mt-8 border-t border-brand-gray-border pt-6">
                <p className="text-brand-black font-semibold mb-3">Votre connexion pour l'IPTV :</p>
                <ul className="space-y-2.5">
                  {QUALITIES.map((q) => {
                    const ok = result.download >= q.need;
                    return (
                      <li key={q.name} className="flex items-start gap-3">
                        {ok ? <Check size={20} className="text-brand-gold flex-shrink-0 mt-0.5" /> : <X size={20} className="text-brand-red flex-shrink-0 mt-0.5" />}
                        <span className="text-brand-black">
                          {q.name} <span className="text-brand-gray text-sm">· {q.need} Mbit/s · {q.detail}</span>
                        </span>
                      </li>
                    );
                  })}
                  <li className="flex items-start gap-3">
                    {pingOk ? <Check size={20} className="text-brand-gold flex-shrink-0 mt-0.5" /> : <X size={20} className="text-brand-red flex-shrink-0 mt-0.5" />}
                    <span className="text-brand-black">
                      Stabilité {pingOk ? 'bonne' : 'à surveiller'} <span className="text-brand-gray text-sm">· latence sous 100 ms et gigue faible recommandées</span>
                    </span>
                  </li>
                </ul>
                <p className="text-brand-gray text-sm mt-4">
                  {hdStreams >= 1
                    ? `Environ ${hdStreams} écran${hdStreams > 1 ? 's' : ''} en HD simultané${hdStreams > 1 ? 's' : ''} avec ce débit.`
                    : "Ce débit est trop faible pour une lecture confortable : essayez en câble Ethernet ou plus près de la box."}
                </p>
                <div className="mt-6 rounded-xl border border-brand-gold/40 p-5">
                  <p className="text-brand-black font-semibold mb-1">
                    {result.download >= 7 ? 'Votre connexion est prête pour l’IPTV.' : 'Améliorez votre connexion, puis testez l’IPTV.'}
                  </p>
                  <p className="text-sm text-brand-gray mb-4">Vérifiez la qualité réelle avec 24 h d'essai gratuit, sans carte bancaire.</p>
                  <button
                    type="button"
                    onClick={() => window.dispatchEvent(new CustomEvent('open-trial'))}
                    className="w-full min-h-[50px] inline-flex items-center justify-center gap-2 bg-brand-gold hover:opacity-90 text-white font-semibold rounded-lg"
                  >
                    Essayer 24 h gratuitement <ArrowRight size={18} />
                  </button>
                </div>
              </div>
            )}
          </div>
          <p className="max-w-xl mx-auto text-xs text-brand-gray text-center mt-3">
            Le test télécharge au maximum 32 Mo depuis nos serveurs. Aucune donnée personnelle n'est collectée.
          </p>
        </section>

        <section className="px-4 py-14 bg-brand-offwhite border-t border-brand-gray-border">
          <div className="max-w-3xl mx-auto blog-body space-y-10 text-brand-gray text-[17px]">
            <section>
              <h2>Quel débit pour l'IPTV ?</h2>
              <p>
                Le débit nécessaire dépend de la qualité de l'image et du nombre d'écrans utilisés en même temps. Voici les repères à
                retenir, <strong>par écran</strong> :
              </p>
              <table>
                <thead><tr><th>Qualité</th><th>Débit conseillé</th><th>Usage</th></tr></thead>
                <tbody>
                  {QUALITIES.map((q) => <tr key={q.name}><td>{q.name}</td><td>{q.need} Mbit/s</td><td>{q.detail}</td></tr>)}
                </tbody>
              </table>
              <p>
                Exemple : deux personnes qui regardent un match en Full HD et une série en HD ont besoin d'environ 15 + 7 = 22 Mbit/s
                stables. Nos abonnements permettent jusqu'à 4 écrans simultanés : voir les <Link to="/tarifs">tarifs</Link>.
              </p>
            </section>

            <section>
              <h2>Résultat trop faible ? 5 façons d'améliorer votre débit</h2>
              <ol>
                <li><strong>Passez en câble Ethernet</strong> entre la box et la TV ou le boîtier : c'est la solution la plus efficace.</li>
                <li><strong>Utilisez le Wi-Fi 5 GHz</strong> plutôt que 2,4 GHz, et rapprochez l'appareil de la box.</li>
                <li><strong>Redémarrez la box internet</strong> (30 secondes débranchée) si elle n'a pas été relancée depuis longtemps.</li>
                <li><strong>Mettez en pause les téléchargements</strong> et les mises à jour sur les autres appareils pendant le visionnage.</li>
                <li><strong>Baissez la qualité</strong> (HD au lieu de 4K) sur les chaînes qui saccadent aux heures de pointe.</li>
              </ol>
              <p>
                Si le débit est bon mais que l'image coupe encore, la cause est ailleurs : consultez{' '}
                <Link to="/blog/iptv-qui-coupe">IPTV qui coupe ou qui freeze : 8 solutions</Link>.
              </p>
            </section>

            <section>
              <h2>Faire le test sur le bon appareil</h2>
              <p>
                Un test fait sur votre téléphone près de la box ne reflète pas ce que reçoit la télévision au salon. Pour un résultat
                utile, ouvrez cette page sur l'appareil qui lit l'IPTV (navigateur de la Smart TV, de la box Android ou du Fire Stick)
                ou, à défaut, sur un téléphone placé à côté de la télévision.
              </p>
              <p>
                Selon votre appareil, suivez ensuite le guide d'installation adapté :{' '}
                <Link to="/appareils/samsung-tv">Samsung</Link>, <Link to="/appareils/lg-tv">LG</Link>,{' '}
                <Link to="/appareils/fire-stick">Fire Stick</Link>, <Link to="/appareils/freebox">Freebox</Link>,{' '}
                <Link to="/appareils/android-tv">Android TV</Link>.
              </p>
            </section>

            <section>
              <h2>Questions fréquentes</h2>
              {faqs.map(({ q, a }) => (
                <div key={q}>
                  <h3>{q}</h3>
                  <p>{a}</p>
                </div>
              ))}
            </section>

            <p className="flex items-center gap-2 text-sm">
              <Wifi size={16} className="text-brand-gold" />
              Partagez ce test : <span className="text-brand-black">franceiptv.stream/test-debit-iptv</span>
            </p>
          </div>
        </section>
      </div>
    </>
  );
};

export default TestDebit;
